"----------------------------------------------------------
" Fundamental Configuration
"----------------------------------------------------------
syntax enable
filetype indent on
filetype plugin on
set encoding=utf-8
set shell=$SHELL
set incsearch

"----------------------------------------------------------
" Visual Configuration
"----------------------------------------------------------
colorscheme retrobox
set termguicolors
set background=dark
set number
set relativenumber
set cursorline
set laststatus=2
set nowrap
set guiheadroom=0

hi CursorLineNr gui=bold cterm=bold term=bold guibg=#303030
hi Normal guibg=NONE ctermbg=NONE

"----------------------------------------------------------
" Editing Behavior
"----------------------------------------------------------
set nospell
set hidden
set noexpandtab
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set confirm

"----------------------------------------------------------
" File Management
"----------------------------------------------------------
set nobackup
set noswapfile
set wildmenu
set wildcharm=<Tab>

"----------------------------------------------------------
" Status Line Configuration
"----------------------------------------------------------
set statusline=
set statusline+=%#Error#%{(mode()=='n')?'\ \ NORMAL\ ':''}
set statusline+=%#Search#%{(mode()=='i')?'\ \ INSERT\ ':''}
set statusline+=%#DiffChange#%{(mode()=='R')?'\ \ REPLACE\ ':''}
set statusline+=%#DiffText#%{(mode()=='v')?'\ \ VISUAL\ ':''}
set statusline+=%#DiffAdd#%{(mode()=='c')?'\ \ COMMAND\ ':''}
set statusline+=%m%*
set statusline+=%#DiffAdd#\ %<%F%*
set statusline+=%#Directory#
set statusline+=\%=
set statusline+=%#Directory#
set statusline+=%#DiffAdd#\ %Y\ %*
set statusline+=\ %c\ %l/%L\ %P\ 

"----------------------------------------------------------
" Key Mappings
"----------------------------------------------------------
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
nnoremap <silent> q :q<CR>
nnoremap <silent> w :w<CR>zz
nnoremap <silent> <C-j> <C-w>j
nnoremap <silent> <C-k> <C-w>k
vnoremap <leader>y :w !wl-copy<CR><CR>
nnoremap <leader>p :r !wl-paste<CR>
nnoremap vv <C-v><CR>
inoremap jj <Esc>

"----------------------------------------------------------
" Replace command
"----------------------------------------------------------
nnoremap <silent> r :exec '%s/' . input('Pattern: ') . '/' . input('Replace: ') . '/g'<CR>

"----------------------------------------------------------
" Autocomplete suggestions in tab
"----------------------------------------------------------
inoremap <expr> <Tab> getline('.')[col('.')-2] !~ '^\s\?$' \|\| pumvisible() ? '<C-N>' : '<Tab>'

"----------------------------------------------------------
" Back to line when exit
"----------------------------------------------------------
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

"----------------------------------------------------------
" ALE
"----------------------------------------------------------
"let g:ale_linters = {'cpp': ['clangd']}
let g:ale_linters = {'cpp': []}
let g:ale_fixers = {'cpp': ['clang-format']}
let g:ale_fix_on_save = 1
