#!/bin/bash
tmp=$(mktemp screenshot-XXXXXXXXXXXX.png)
if maim -s "$tmp"; then
    output=~/Pictures/Screenshot-$(date +%F-%H-%M-%S | tr ' ' '_').png
    cp "$tmp" "$output"
    xclip -selection clipboard -t image/png -i "$tmp"
    rm -f "$tmp"
else
    rm -f "$tmp"
fi

